- hosts: all
  roles:
    - role: Prereqs
    - role: Modify_IP_Tables
    - role: Update_Kernel
    - role: Install_And_Configure_PostgreSQL
      when: "'web' in group_names"
    - role: Download_And_Install_ConcourseCI
    - role: Generate_And_Setup_RSA_Keys
    - role: Exchange_Keys
    - role: Configure_Environment_And_Systemd_Service
    - role: Deploy_Sample_Pipelines
  become: yes 
