---

- name: Add ELRepo
  yum:
    name: "{{ elrepo_repo_url }}"
    state: present

- name: Install latest mainline kernel
  yum:
    name: kernel-ml
    state: latest
    enablerepo: elrepo-kernel
  register: yum_updates

- debug:
        var: yum_updates.changes.installed

- name: Remake grub config to pick up new kernel
  shell: |
    grub2-set-default 0
    grub2-mkconfig -o /boot/grub2/grub.cfg
  when: '"kernel-ml" in yum_updates.changes.installed'

- name: Restart server to ensure configuration changes take hold
  shell: 'sleep 2 && shutdown -r now "Reboot triggered by Ansible" && sleep 5'
  async: 1
  poll: 0
  when: '"kernel-ml" in yum_updates.changes.installed'

- name: Wait for the server to restart
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      port=22
      delay=10
