- name: Add concourse group
  group:
    name: concourse

- name: Add concourse user
  user:
    name: concourse
    group: concourse
    system: yes
    password: "{{ concourse_user_password }}"

- name: Create a new directory /etc/concourse
  file:
    path: /etc/concourse
    state: directory
    owner: concourse
    group: concourse

- name: Delete old keys
  file:
    path: "{{ item }}"
    state: absent
    force: yes
  with_items:
    - /etc/concourse/session_signing_key
    - /etc/concourse/tsa_host_key
    - /etc/concourse/worker_key

- name: ssh-keygen in actions
  shell:  yes y | ssh-keygen -t rsa -q -N '' -f {{ item }}
  with_items:
    - /etc/concourse/session_signing_key
    - /etc/concourse/tsa_host_key
    - /etc/concourse/worker_key

