- name: Copy hello-world pipeline example
  template:
    src: "{{ item }}"
    dest: /home/concourse
    owner: concourse
    group: concourse
    mode: '0755'
  with_items:
    - hello-world.yml
    - hello_pipeline.sh
    - set-pipelines.yml
    - set_pipelines.sh
    - initial_login.sh
  when: "'web' in group_names"
  
