- name: Stop and disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- name: Put SELinux in permissive mode
  selinux:
    policy: targeted
    state: permissive

- name: Disable SELinux
  selinux:
    state: disabled

